name: dummy

on:
  pull_request:
    branches: [ "master" ]
  pull_request_target:
    branches: [ "master" ]

jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: git rev-parse HEAD 
